### ISSUE TITLE
TODO for v1.0

### ISSUE THREAD

**Issue by usefulthink** [beyondscreen/node-rpi-ws281x-native#29]
## node-module and native parts
- [x] support for multiple PWM channels (issue: #18)
- [ ] support for different binary-formats (i.e. `CanvasPixelData`, `Uint8Array` and `Uint32Array`, `Buffer`/`ArrayBuffer`)
- [x] a tiny bit more abstraction: the public api should be fully implemented in Javascript, so the underlying native-implementation is able to move without breaking BC
- [ ] generic implementation for per pixel and full data-array operations (color-correction, channel-splitting, whatever..)
- [ ] switch to `node-pre-gyp` instead of `node-gyp`
## rpi_ws281x
- [ ] update library to use the original repository again, now that a lot of compatibility-work has happened there

**Comment by usefulthink** [comment]
### changes required to support multiple channels

As the client-side code does not directly call the native implementations, it should be possible to change the implementation without breaking compatibility on the client-side.

 - [`<rpi-ws281x.cc>.init()`][1]
   - accept parameters for both channels, ideally two objects where the second one is optional, moving the ledCount into the object. 
   - initialize both channels before calling `ws281x_init()`
 - [`<rpi-ws281x.cc.render()`][2]
   - should accept two byte-arrays if both channels are used (this is preferable over accepting a channel-number b/c the call will always synchronously write out data for both channels

 - implementations of the javascript-bindings in [`ws281x-native.js`][3] should maintain their behavior but need to be update to the changes above.
 - there should be an updated version of the interface supporting multiple channels, this would be open for discussion how this could look.

[1]: https://github.com/beyondscreen/node-rpi-ws281x-native/blob/master/src/rpi-ws281x.cc#L61
[2]: https://github.com/beyondscreen/node-rpi-ws281x-native/blob/master/src/rpi-ws281x.cc#L32
[3]: https://github.com/beyondscreen/node-rpi-ws281x-native/blob/master/lib/ws281x-native.js#L121

**Comment by ben0bi** [comment]
I could not install it with nodejs v6 and I could not install nodejs v4.
For me, it works with nodejs v0.12.

Would like to mark this as todo, compatibility for nodejs >= v4
(Or is it my system? I use the RetroPie-Distro and LXDE as window manager. Multipurpose is the key.)

Regards,
ben0bi

**Comment by ben0bi** [comment]
I could not install it with nodejs v6 and I could not install nodejs v4.
For me, it works with nodejs v0.12.

Would like to mark this as todo, compatibility for nodejs >= v4
(Or is it my system? I use the RetroPie-Distro and LXDE as window manager. Multipurpose is the key.)

Regards,
ben0bi

**Comment by ben0bi** [comment]
I could not install it with nodejs v6 and I could not install nodejs v4.
For me, it works with nodejs v0.12.

Would like to mark this as todo, compatibility for nodejs >= v4
(Or is it my system? I use the RetroPie-Distro and LXDE as window manager. Multipurpose is the key.)

Regards,
ben0bi

**Comment by usefulthink** [comment]
@ben0bi haven't touched this project in a while so it can very wel be that something got a bit outdated. Can you provide some more details about that failed installation attempt? Are there compiler-errors or something like that?

**Comment by usefulthink** [comment]
I moved this into a seperate issue.

**Comment by usefulthink** [comment]
see #67
